In [ ]:
import pandas as pd
df = pd.read_csv("/content/blind_all_keywords_final.csv")
df

,검색어,제목,날짜,작성자,본문,댓글
0,층간소음,층간소음 방지 매트 언제까지 깔아놓으세요?,2026.05.22. 13:19,큑큑,첫째가 돌무렵부터 깔아놓은 층간소음매트\n지금 그 애가 11살이에요.남자아이라 활동...,[me before U] 둘째 8살까지는...\n[대댓글시비충극혐] 애가 둘이면 더...
1,층간소음,층간소음은 어디까지 이해해야 하나요?,2026.05.21. 22:48,더 멋진 오늘,윗층에 유치원 다니는 쌍둥이들이 살아요\n처음에 이사왔을때 너무 뛰어다니길래\n한번...,[두쫑크] 층간소음은 참으면 계속 참아야 합니다..\n[더 멋진 오늘] 그럼 참지 ...
2,층간소음,변비 있는분들 운동 해보세요,2026.05.21. 17:01,sthdeayikfv,요구르트 먹어요 겨우겨우였는데 장이 흔들릴 정도의 댄스를 하니까 그냥 거의 매일 입...,[alclsshadk] 5키로씩 러닝 뛰었을 때 장은 안 변하던데요........ㅜ...
3,층간소음,층간소음 발망치...가서 얘기해도 될까요..ㅜ,2026.05.21. 14:05,반짝이핑쿠핑쿠,10년동안 살면서 윗집복은 있었는데..\n이번에 윗집 새로 이사오고 층간소음이 시달...,[복슝야] 발망치 소리는 얘기해야죠\n[반짝이핑쿠핑쿠] 네..온갖상상회로 올리는데 ...
4,층간소음,층간소음 실내화,2026.05.21. 12:54,일년하루같이,윗층 노부부 사시는데요\n좋으신분들이에요 오며가며 인사도 하구요\n명절때 너무 시끄...,[고랴니] 기분 나빠할거 같긴 해요
...,...,...,...,...,...,...
2033,화장실,물탱크 청소중.화장실 가고싶네요😂,2026.05.22. 09:56,또순이좋아,물탱크 청소중이라 물잠궈놔서 새벽부터 물이 안나와요.\n세탁기에 물받아놔서 쓰긴한데...,[또순이좋아] 아파트가 아니라서 상가가 없어요ㅜㅜ
2034,화장실,증상:쓰러질것같을때 대변보면 괜찮아지는느낌????,2026.05.22. 09:26,긍정님0,어디 물어보기 애매하고 민망해서 글올려봅니다\n집안일하고 있는평범한 날이였는데요\n...,[숑이1] 그거 미주신경성실신이요 ㅜㅜ 저도 그래요\n[긍정님0] 그럼 따로 약을 ...
2035,화장실,"화장실에 욕실화,몇개세요?",2026.05.22. 09:22,아오이오웅,저흰 발사이즈 250과 290이 같이 쓰는 욕실예요.\n문앞에 두개씩 놓자니 번잡하...,[내 얘기 금지] 큰사이즈로 하나만 둬요 화장실에서 잠깐 쓰는건데요\n[jivaka...
2036,화장실,런닝하시는 분들 무릎 살짝?아파도 뛰시나요.?,2026.05.22. 07:07,헤헤0414,"며질전부터 무릎이 마구 아프다기보단,\n무릎 굽힐때 아픈 느낌? 불편한 느낌이 있어...",[호반영] 아이구야 안되요 빨리병원가봐요\n엄청오래가던데요 무릎ㅠㅠ\n[반짝이는 메...
2037,화장실,귀신프로 보고 혼자 못자는 아들 어떡하죠? 하ㅜㅜ,2026.05.21. 23:45,처음처럼살기를,중1이에요\n학교에서 선생님이\n귀신나오는 프로그램을 틀어주셔서\n애들이 봤대요\n...,[오늘 뭐 먹지] ㅠㅠㅠ 저도 중1때 공포영화보고 무서워서 힘들었어요..\n잘때 불...

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# 코랩 konlpy 실행
!curl -s https://raw.githubusercontent.com/teddylee777/machine-learning/master/99-Misc/01-Colab/mecab-colab.sh | bash

# Mecab 설치 후 Google Drive에 복사
!cp -r /usr/local/lib/mecab /content/drive/MyDrive/mecab
!cp -r /usr/local/etc/mecabrc /content/drive/MyDrive/mecab

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
--2026-05-26 00:35:29--  https://www.dropbox.com/s/9xls0tgtf3edgns/mecab-0.996-ko-0.9.2.tar.gz?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.85.18, 2620:100:6035:18::a27d:5512
Connecting to www.dropbox.com (www.dropbox.com)|162.125.85.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.dropbox.com/scl/fi/g8l6dlu5a3ebovcdymluq/mecab-0.996-ko-0.9.2.tar.gz?rlkey=xlooryouhr1l2ufqbt93ohfvy&dl=1 [following]
--2026-05-26 00:35:30--  https://www.dropbox.com/scl/fi/g8l6dlu5a3ebovcdymluq/mecab-0.996-ko-0.9.2.tar.gz?rlkey=xlooryouhr1l2ufqbt93ohfvy&dl=1
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc9c34cc3d6321ba5fe1c3fccf61.dl.dropboxusercontent.com/cd/0/inline/DBLvv1fWo_FX1KXNpjkZxmvFl86JavXBtZkEgYzGRsllXBeBWt4O1ylogk5ALA6EWaB_Fou0Ba1Thjj_DTrcL8aYORg5I4nRGB1VTBA93BgZOhbY7a2ifVrNY0aJsLmQWWRr_Ar5XrheBf36mOQjJgeS/file?dl=1# [following]
--2026-05-26 00:35:30--  https://uc9c34cc3d6321ba5fe1c3fccf61.dl.dropboxusercontent.com/cd/0/inline/DBLvv1fWo_FX1KXNpjkZxmvFl86JavXBtZkEgYzGRsllXBeBWt4O1ylogk5ALA6EWaB_Fou0Ba1Thjj_DTrcL8aYORg5I4nRGB1VTBA93BgZOhbY7a2ifVrNY0aJsLmQWWRr_Ar5XrheBf36mOQjJgeS/file?dl=1
Resolving uc9c34cc3d6321ba5fe1c3fccf61.dl.dropboxusercontent.com (uc9c34cc3d6321ba5fe1c3fccf61.dl.dropboxusercontent.com)... 162.125.85.15, 2620:100:6023:15::a27d:430f
Connecting to uc9c34cc3d6321ba5fe1c3fccf61.dl.dropboxusercontent.com (uc9c34cc3d6321ba5fe1c3fccf61.dl.dropboxusercontent.com)|162.125.85.15|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /cd/0/inline2/DBJDSO3jFgfkqKhXd4pEJyj6ptXH1J0afvOc64rvkBrqK6yJ1SwwR_zl4XVFa0ans9aHwgFC_ekkBzYXb0oBhRvzx15vSetpYufkkWi9fe1y3NL3Of7Acko8jdSOvtCikoTrZGugk0X1GJnVzvyx2PQk_EqS91HRpVDjpT9N5jQ92SSWnaVTa7jU99vTxHCaGWZtbh7vnki-Zp2PFWdISIRWV3M7n7vwyfMAuxa9cq4vmlMJMdJf30TWORxwdX_Q3zZDPGL31XkZ1yzIeBTZc36ENJE7WzCJivmek4cwWHcBGyw6ekodPYXD4rbSIBKdNlc8R9ETpl-WKHdHCLSkZ_ITZRpgLNvrQPnlZ6CtHeyqR7z-_87PcE13eAlOfUdvF8Y/file?dl=1 [following]
--2026-05-26 00:35:31--  https://uc9c34cc3d6321ba5fe1c3fccf61.dl.dropboxusercontent.com/cd/0/inline2/DBJDSO3jFgfkqKhXd4pEJyj6ptXH1J0afvOc64rvkBrqK6yJ1SwwR_zl4XVFa0ans9aHwgFC_ekkBzYXb0oBhRvzx15vSetpYufkkWi9fe1y3NL3Of7Acko8jdSOvtCikoTrZGugk0X1GJnVzvyx2PQk_EqS91HRpVDjpT9N5jQ92SSWnaVTa7jU99vTxHCaGWZtbh7vnki-Zp2PFWdISIRWV3M7n7vwyfMAuxa9cq4vmlMJMdJf30TWORxwdX_Q3zZDPGL31XkZ1yzIeBTZc36ENJE7WzCJivmek4cwWHcBGyw6ekodPYXD4rbSIBKdNlc8R9ETpl-WKHdHCLSkZ_ITZRpgLNvrQPnlZ6CtHeyqR7z-_87PcE13eAlOfUdvF8Y/file?dl=1
Reusing existing connection to uc9c34cc3d6321ba5fe1c3fccf61.dl.dropboxusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 1414979 (1.3M) [application/binary]
Saving to: ‘mecab-0.996-ko-0.9.2.tar.gz?dl=1’

mecab-0.996-ko-0.9. 100%[===================>]   1.35M  4.09MB/s    in 0.3s

2026-05-26 00:35:32 (4.09 MB/s) - ‘mecab-0.996-ko-0.9.2.tar.gz?dl=1’ saved [1414979/1414979]

mecab-0.996-ko-0.9.2/
mecab-0.996-ko-0.9.2/example/
mecab-0.996-ko-0.9.2/example/example.cpp
mecab-0.996-ko-0.9.2/example/example_lattice.cpp
mecab-0.996-ko-0.9.2/example/example_lattice.c
mecab-0.996-ko-0.9.2/example/example.c
mecab-0.996-ko-0.9.2/example/thread_test.cpp
mecab-0.996-ko-0.9.2/mecab-config.in
mecab-0.996-ko-0.9.2/man/
mecab-0.996-ko-0.9.2/man/Makefile.am
mecab-0.996-ko-0.9.2/man/mecab.1
mecab-0.996-ko-0.9.2/man/Makefile.in
mecab-0.996-ko-0.9.2/mecab.iss.in
mecab-0.996-ko-0.9.2/config.guess
mecab-0.996-ko-0.9.2/README
mecab-0.996-ko-0.9.2/COPYING
mecab-0.996-ko-0.9.2/CHANGES.md
mecab-0.996-ko-0.9.2/README.md
mecab-0.996-ko-0.9.2/INSTALL
mecab-0.996-ko-0.9.2/config.sub
mecab-0.996-ko-0.9.2/configure.in
mecab-0.996-ko-0.9.2/swig/
mecab-0.996-ko-0.9.2/swig/Makefile
mecab-0.996-ko-0.9.2/swig/version.h.in
mecab-0.996-ko-0.9.2/swig/version.h
mecab-0.996-ko-0.9.2/swig/MeCab.i
mecab-0.996-ko-0.9.2/aclocal.m4
mecab-0.996-ko-0.9.2/LGPL
mecab-0.996-ko-0.9.2/Makefile.am
mecab-0.996-ko-0.9.2/configure
mecab-0.996-ko-0.9.2/tests/
mecab-0.996-ko-0.9.2/tests/autolink/
mecab-0.996-ko-0.9.2/tests/autolink/unk.def
mecab-0.996-ko-0.9.2/tests/autolink/dicrc
mecab-0.996-ko-0.9.2/tests/autolink/dic.csv
mecab-0.996-ko-0.9.2/tests/autolink/test
mecab-0.996-ko-0.9.2/tests/autolink/char.def
mecab-0.996-ko-0.9.2/tests/autolink/matrix.def
mecab-0.996-ko-0.9.2/tests/autolink/test.gld
mecab-0.996-ko-0.9.2/tests/t9/
mecab-0.996-ko-0.9.2/tests/t9/unk.def
mecab-0.996-ko-0.9.2/tests/t9/ipadic.pl
mecab-0.996-ko-0.9.2/tests/t9/dicrc
mecab-0.996-ko-0.9.2/tests/t9/dic.csv
mecab-0.996-ko-0.9.2/tests/t9/test
mecab-0.996-ko-0.9.2/tests/t9/char.def
mecab-0.996-ko-0.9.2/tests/t9/matrix.def
mecab-0.996-ko-0.9.2/tests/t9/mkdic.pl
mecab-0.996-ko-0.9.2/tests/t9/test.gld
mecab-0.996-ko-0.9.2/tests/cost-train/
mecab-0.996-ko-0.9.2/tests/cost-train/ipa.train
mecab-0.996-ko-0.9.2/tests/cost-train/ipa.test
mecab-0.996-ko-0.9.2/tests/cost-train/seed/
mecab-0.996-ko-0.9.2/tests/cost-train/seed/rewrite.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/feature.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/unk.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/dicrc
mecab-0.996-ko-0.9.2/tests/cost-train/seed/dic.csv
mecab-0.996-ko-0.9.2/tests/cost-train/seed/char.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/matrix.def
mecab-0.996-ko-0.9.2/tests/run-eval.sh
mecab-0.996-ko-0.9.2/tests/run-cost-train.sh
mecab-0.996-ko-0.9.2/tests/Makefile.am
mecab-0.996-ko-0.9.2/tests/katakana/
mecab-0.996-ko-0.9.2/tests/katakana/unk.def
mecab-0.996-ko-0.9.2/tests/katakana/dicrc
mecab-0.996-ko-0.9.2/tests/katakana/dic.csv
mecab-0.996-ko-0.9.2/tests/katakana/test
mecab-0.996-ko-0.9.2/tests/katakana/char.def
mecab-0.996-ko-0.9.2/tests/katakana/matrix.def
mecab-0.996-ko-0.9.2/tests/katakana/test.gld
mecab-0.996-ko-0.9.2/tests/eval/
mecab-0.996-ko-0.9.2/tests/eval/answer
mecab-0.996-ko-0.9.2/tests/eval/system
mecab-0.996-ko-0.9.2/tests/eval/test.gld
mecab-0.996-ko-0.9.2/tests/shiin/
mecab-0.996-ko-0.9.2/tests/shiin/unk.def
mecab-0.996-ko-0.9.2/tests/shiin/dicrc
mecab-0.996-ko-0.9.2/tests/shiin/dic.csv
mecab-0.996-ko-0.9.2/tests/shiin/test
mecab-0.996-ko-0.9.2/tests/shiin/char.def
mecab-0.996-ko-0.9.2/tests/shiin/matrix.def
mecab-0.996-ko-0.9.2/tests/shiin/mkdic.pl
mecab-0.996-ko-0.9.2/tests/shiin/test.gld
mecab-0.996-ko-0.9.2/tests/latin/
mecab-0.996-ko-0.9.2/tests/latin/unk.def
mecab-0.996-ko-0.9.2/tests/latin/dicrc
mecab-0.996-ko-0.9.2/tests/latin/dic.csv
mecab-0.996-ko-0.9.2/tests/latin/test
mecab-0.996-ko-0.9.2/tests/latin/char.def
mecab-0.996-ko-0.9.2/tests/latin/matrix.def
mecab-0.996-ko-0.9.2/tests/latin/test.gld
mecab-0.996-ko-0.9.2/tests/chartype/
mecab-0.996-ko-0.9.2/tests/chartype/unk.def
mecab-0.996-ko-0.9.2/tests/chartype/dicrc
mecab-0.996-ko-0.9.2/tests/chartype/dic.csv
mecab-0.996-ko-0.9.2/tests/chartype/test
mecab-0.996-ko-0.9.2/tests/chartype/char.def
mecab-0.996-ko-0.9.2/tests/chartype/matrix.def
mecab-0.996-ko-0.9.2/tests/chartype/test.gld
mecab-0.996-ko-0.9.2/tests/run-dics.sh
mecab-0.996-ko-0.9.2/tests/ngram/
mecab-0.996-ko-0.9.2/tests/ngram/unk.def
mecab-0.996-ko-0.9.2/tests/ngram/dicrc
mecab-0.996-ko-0.9.2/tests/ngram/dic.csv
mecab-0.996-ko-0.9.2/tests/ngram/test
mecab-0.996-ko-0.9.2/tests/ngram/char.def
mecab-0.996-ko-0.9.2/tests/ngram/matrix.def
mecab-0.996-ko-0.9.2/tests/ngram/test.gld
mecab-0.996-ko-0.9.2/tests/Makefile.in
mecab-0.996-ko-0.9.2/ltmain.sh
mecab-0.996-ko-0.9.2/config.rpath
mecab-0.996-ko-0.9.2/config.h.in
mecab-0.996-ko-0.9.2/mecabrc.in
mecab-0.996-ko-0.9.2/GPL
mecab-0.996-ko-0.9.2/Makefile.train
mecab-0.996-ko-0.9.2/ChangeLog
mecab-0.996-ko-0.9.2/install-sh
mecab-0.996-ko-0.9.2/AUTHORS
mecab-0.996-ko-0.9.2/doc/
mecab-0.996-ko-0.9.2/doc/bindings.html
mecab-0.996-ko-0.9.2/doc/posid.html
mecab-0.996-ko-0.9.2/doc/unk.html
mecab-0.996-ko-0.9.2/doc/learn.html
mecab-0.996-ko-0.9.2/doc/format.html
mecab-0.996-ko-0.9.2/doc/libmecab.html
mecab-0.996-ko-0.9.2/doc/mecab.css
mecab-0.996-ko-0.9.2/doc/feature.html
mecab-0.996-ko-0.9.2/doc/Makefile.am
mecab-0.996-ko-0.9.2/doc/soft.html
mecab-0.996-ko-0.9.2/doc/en/
mecab-0.996-ko-0.9.2/doc/en/bindings.html
mecab-0.996-ko-0.9.2/doc/dic-detail.html
mecab-0.996-ko-0.9.2/doc/flow.png
mecab-0.996-ko-0.9.2/doc/mecab.html
mecab-0.996-ko-0.9.2/doc/index.html
mecab-0.996-ko-0.9.2/doc/result.png
mecab-0.996-ko-0.9.2/doc/doxygen/
mecab-0.996-ko-0.9.2/doc/doxygen/tab_a.png
mecab-0.996-ko-0.9.2/doc/doxygen/globals_eval.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Tagger-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/functions_vars.html
mecab-0.996-ko-0.9.2/doc/doxygen/doxygen.css
mecab-0.996-ko-0.9.2/doc/doxygen/tab_r.gif
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Lattice.html
mecab-0.996-ko-0.9.2/doc/doxygen/functions.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Tagger.html
mecab-0.996-ko-0.9.2/doc/doxygen/mecab_8h_source.html
mecab-0.996-ko-0.9.2/doc/doxygen/tabs.css
mecab-0.996-ko-0.9.2/doc/doxygen/nav_f.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_b.png
mecab-0.996-ko-0.9.2/doc/doxygen/globals.html
mecab-0.996-ko-0.9.2/doc/doxygen/nav_h.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_h.png
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Model.html
mecab-0.996-ko-0.9.2/doc/doxygen/globals_func.html
mecab-0.996-ko-0.9.2/doc/doxygen/closed.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_l.gif
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__path__t-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/functions_func.html
mecab-0.996-ko-0.9.2/doc/doxygen/globals_type.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Lattice-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__node__t.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespacemembers_func.html
mecab-0.996-ko-0.9.2/doc/doxygen/tab_s.png
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__dictionary__info__t-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespacemembers_type.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Model-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__dictionary__info__t.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespaces.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespacemembers.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespaceMeCab.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__path__t.html
mecab-0.996-ko-0.9.2/doc/doxygen/files.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__node__t-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/index.html
mecab-0.996-ko-0.9.2/doc/doxygen/annotated.html
mecab-0.996-ko-0.9.2/doc/doxygen/globals_defs.html
mecab-0.996-ko-0.9.2/doc/doxygen/classes.html
mecab-0.996-ko-0.9.2/doc/doxygen/mecab_8h-source.html
mecab-0.996-ko-0.9.2/doc/doxygen/doxygen.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_b.gif
mecab-0.996-ko-0.9.2/doc/doxygen/bc_s.png
mecab-0.996-ko-0.9.2/doc/doxygen/open.png
mecab-0.996-ko-0.9.2/doc/doxygen/mecab_8h.html
mecab-0.996-ko-0.9.2/doc/dic.html
mecab-0.996-ko-0.9.2/doc/partial.html
mecab-0.996-ko-0.9.2/doc/feature.png
mecab-0.996-ko-0.9.2/doc/Makefile.in
mecab-0.996-ko-0.9.2/missing
mecab-0.996-ko-0.9.2/BSD
mecab-0.996-ko-0.9.2/NEWS
mecab-0.996-ko-0.9.2/mkinstalldirs
mecab-0.996-ko-0.9.2/src/
mecab-0.996-ko-0.9.2/src/dictionary.h
mecab-0.996-ko-0.9.2/src/writer.h
mecab-0.996-ko-0.9.2/src/utils.h
mecab-0.996-ko-0.9.2/src/string_buffer.cpp
mecab-0.996-ko-0.9.2/src/tokenizer.cpp
mecab-0.996-ko-0.9.2/src/make.bat
mecab-0.996-ko-0.9.2/src/mecab.h
mecab-0.996-ko-0.9.2/src/freelist.h
mecab-0.996-ko-0.9.2/src/string_buffer.h
mecab-0.996-ko-0.9.2/src/learner_tagger.h
mecab-0.996-ko-0.9.2/src/dictionary_compiler.cpp
mecab-0.996-ko-0.9.2/src/eval.cpp
mecab-0.996-ko-0.9.2/src/mecab-system-eval.cpp
mecab-0.996-ko-0.9.2/src/darts.h
mecab-0.996-ko-0.9.2/src/param.h
mecab-0.996-ko-0.9.2/src/char_property.h
mecab-0.996-ko-0.9.2/src/learner_node.h
mecab-0.996-ko-0.9.2/src/mecab-dict-gen.cpp
mecab-0.996-ko-0.9.2/src/mecab-dict-index.cpp
mecab-0.996-ko-0.9.2/src/winmain.h
mecab-0.996-ko-0.9.2/src/thread.h
mecab-0.996-ko-0.9.2/src/context_id.cpp
mecab-0.996-ko-0.9.2/src/Makefile.am
mecab-0.996-ko-0.9.2/src/connector.h
mecab-0.996-ko-0.9.2/src/common.h
mecab-0.996-ko-0.9.2/src/dictionary_rewriter.cpp
mecab-0.996-ko-0.9.2/src/Makefile.msvc.in
mecab-0.996-ko-0.9.2/src/dictionary_rewriter.h
mecab-0.996-ko-0.9.2/src/feature_index.h
mecab-0.996-ko-0.9.2/src/iconv_utils.cpp
mecab-0.996-ko-0.9.2/src/char_property.cpp
mecab-0.996-ko-0.9.2/src/mecab-test-gen.cpp
mecab-0.996-ko-0.9.2/src/tagger.cpp
mecab-0.996-ko-0.9.2/src/mecab-cost-train.cpp
mecab-0.996-ko-0.9.2/src/learner.cpp
mecab-0.996-ko-0.9.2/src/dictionary.cpp
mecab-0.996-ko-0.9.2/src/lbfgs.cpp
mecab-0.996-ko-0.9.2/src/ucs.h
mecab-0.996-ko-0.9.2/src/writer.cpp
mecab-0.996-ko-0.9.2/src/learner_tagger.cpp
mecab-0.996-ko-0.9.2/src/lbfgs.h
mecab-0.996-ko-0.9.2/src/libmecab.cpp
mecab-0.996-ko-0.9.2/src/tokenizer.h
mecab-0.996-ko-0.9.2/src/mecab.cpp
mecab-0.996-ko-0.9.2/src/utils.cpp
mecab-0.996-ko-0.9.2/src/dictionary_generator.cpp
mecab-0.996-ko-0.9.2/src/param.cpp
mecab-0.996-ko-0.9.2/src/context_id.h
mecab-0.996-ko-0.9.2/src/mmap.h
mecab-0.996-ko-0.9.2/src/viterbi.h
mecab-0.996-ko-0.9.2/src/viterbi.cpp
mecab-0.996-ko-0.9.2/src/stream_wrapper.h
mecab-0.996-ko-0.9.2/src/feature_index.cpp
mecab-0.996-ko-0.9.2/src/nbest_generator.h
mecab-0.996-ko-0.9.2/src/ucstable.h
mecab-0.996-ko-0.9.2/src/nbest_generator.cpp
mecab-0.996-ko-0.9.2/src/iconv_utils.h
mecab-0.996-ko-0.9.2/src/connector.cpp
mecab-0.996-ko-0.9.2/src/Makefile.in
mecab-0.996-ko-0.9.2/src/scoped_ptr.h
mecab-0.996-ko-0.9.2/Makefile.in
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether gcc needs -traditional... no
checking whether make sets $(MAKE)... (cached) yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for library containing strerror... none required
checking whether byte ordering is bigendian... no
checking for ld used by GCC... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking for shared library run path origin... done
checking for iconv... yes
checking for working iconv... yes
checking for iconv declaration...
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking for ANSI C header files... (cached) yes
checking for an ANSI C-conforming const... yes
checking whether byte ordering is bigendian... (cached) no
checking for string.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for stdint.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking sys/times.h usability... yes
checking sys/times.h presence... yes
checking for sys/times.h... yes
checking for sys/types.h... (cached) yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking for sys/types.h... (cached) yes
checking io.h usability... no
checking io.h presence... no
checking for io.h... no
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for off_t... yes
checking for size_t... yes
checking size of char... 1
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking size of long long... 8
checking size of size_t... 8
checking for size_t... (cached) yes

In [ ]:
! pip install kiwipiepy
import pandas as pd
import re
from konlpy.tag import Okt
from kiwipiepy import Kiwi

Collecting kiwipiepy
  Downloading kiwipiepy-0.23.1-cp39-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.3 kB)
Collecting kiwipiepy_model<0.24,>=0.23 (from kiwipiepy)
  Downloading kiwipiepy_model-0.23.0.tar.gz (88.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 8.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from kiwipiepy) (2.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kiwipiepy) (4.67.3)
Downloading kiwipiepy-0.23.1-cp39-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 8.2 MB/s eta 0:00:00
Building wheels for collected packages: kiwipiepy_model
  Building wheel for kiwipiepy_model (setup.py) ... done
  Created wheel for kiwipiepy_model: filename=kiwipiepy_model-0.23.0-py3-none-any.whl size=88067826 sha256=31d0a6a38ebf0c3cfb6fc26d043440a782e16196e18b5b07eb921423ba02503f
  Stored in directory: /root/.cache/pip/wheels/f2/94/da/ff88b4c2305cd1f3effc8001b5f42f16dc9931bcd84d1e77c3
Successfully built kiwipiepy_model
Installing collected packages: kiwipiepy_model, kiwipiepy
Successfully installed kiwipiepy-0.23.1 kiwipiepy_model-0.23.0

# 통합본문 만들기

In [ ]:
import pandas as pd

# 1. 데이터 불러오기 (이미 불러온 상태라면 생략 가능)
# df = pd.read_csv('레몬테라스_층간소음_2023부터.xlsx - Sheet1.csv')

# 2. 식별 정보 제거 (익명성 보장)
if '작성자' in df.columns:
    df = df.drop(columns=['작성자'])

# 3. 결측치(NaN)를 빈 문자열로 변환
df['제목'] = df['제목'].fillna('')
df['본문'] = df['본문'].fillna('')
df['댓글'] = df['댓글'].fillna('')

# 4. '제목', '본문', '댓글'을 합쳐서 '통합본문' 컬럼 생성
# 각 텍스트가 자연스럽게 이어지도록 사이에 공백(' ')을 추가합니다.
df['통합본문'] = df['제목'] + ' ' + df['본문'] + ' ' + df['댓글']

In [ ]:
df

,검색어,제목,날짜,본문,댓글,통합본문
0,층간소음,층간소음 방지 매트 언제까지 깔아놓으세요?,2026.05.22. 13:19,첫째가 돌무렵부터 깔아놓은 층간소음매트\n지금 그 애가 11살이에요.남자아이라 활동...,[me before U] 둘째 8살까지는...\n[대댓글시비충극혐] 애가 둘이면 더...,층간소음 방지 매트 언제까지 깔아놓으세요? 첫째가 돌무렵부터 깔아놓은 층간소음매트\...
1,층간소음,층간소음은 어디까지 이해해야 하나요?,2026.05.21. 22:48,윗층에 유치원 다니는 쌍둥이들이 살아요\n처음에 이사왔을때 너무 뛰어다니길래\n한번...,[두쫑크] 층간소음은 참으면 계속 참아야 합니다..\n[더 멋진 오늘] 그럼 참지 ...,층간소음은 어디까지 이해해야 하나요? 윗층에 유치원 다니는 쌍둥이들이 살아요\n처음...
2,층간소음,변비 있는분들 운동 해보세요,2026.05.21. 17:01,요구르트 먹어요 겨우겨우였는데 장이 흔들릴 정도의 댄스를 하니까 그냥 거의 매일 입...,[alclsshadk] 5키로씩 러닝 뛰었을 때 장은 안 변하던데요........ㅜ...,변비 있는분들 운동 해보세요 요구르트 먹어요 겨우겨우였는데 장이 흔들릴 정도의 댄스...
3,층간소음,층간소음 발망치...가서 얘기해도 될까요..ㅜ,2026.05.21. 14:05,10년동안 살면서 윗집복은 있었는데..\n이번에 윗집 새로 이사오고 층간소음이 시달...,[복슝야] 발망치 소리는 얘기해야죠\n[반짝이핑쿠핑쿠] 네..온갖상상회로 올리는데 ...,층간소음 발망치...가서 얘기해도 될까요..ㅜ 10년동안 살면서 윗집복은 있었는데....
4,층간소음,층간소음 실내화,2026.05.21. 12:54,윗층 노부부 사시는데요\n좋으신분들이에요 오며가며 인사도 하구요\n명절때 너무 시끄...,[고랴니] 기분 나빠할거 같긴 해요,층간소음 실내화 윗층 노부부 사시는데요\n좋으신분들이에요 오며가며 인사도 하구요\n...
...,...,...,...,...,...,...
2033,화장실,물탱크 청소중.화장실 가고싶네요😂,2026.05.22. 09:56,물탱크 청소중이라 물잠궈놔서 새벽부터 물이 안나와요.\n세탁기에 물받아놔서 쓰긴한데...,[또순이좋아] 아파트가 아니라서 상가가 없어요ㅜㅜ,물탱크 청소중.화장실 가고싶네요😂 물탱크 청소중이라 물잠궈놔서 새벽부터 물이 안나와...
2034,화장실,증상:쓰러질것같을때 대변보면 괜찮아지는느낌????,2026.05.22. 09:26,어디 물어보기 애매하고 민망해서 글올려봅니다\n집안일하고 있는평범한 날이였는데요\n...,[숑이1] 그거 미주신경성실신이요 ㅜㅜ 저도 그래요\n[긍정님0] 그럼 따로 약을 ...,증상:쓰러질것같을때 대변보면 괜찮아지는느낌???? 어디 물어보기 애매하고 민망해서 ...
2035,화장실,"화장실에 욕실화,몇개세요?",2026.05.22. 09:22,저흰 발사이즈 250과 290이 같이 쓰는 욕실예요.\n문앞에 두개씩 놓자니 번잡하...,[내 얘기 금지] 큰사이즈로 하나만 둬요 화장실에서 잠깐 쓰는건데요\n[jivaka...,"화장실에 욕실화,몇개세요? 저흰 발사이즈 250과 290이 같이 쓰는 욕실예요.\n..."
2036,화장실,런닝하시는 분들 무릎 살짝?아파도 뛰시나요.?,2026.05.22. 07:07,"며질전부터 무릎이 마구 아프다기보단,\n무릎 굽힐때 아픈 느낌? 불편한 느낌이 있어...",[호반영] 아이구야 안되요 빨리병원가봐요\n엄청오래가던데요 무릎ㅠㅠ\n[반짝이는 메...,"런닝하시는 분들 무릎 살짝?아파도 뛰시나요.? 며질전부터 무릎이 마구 아프다기보단,..."
2037,화장실,귀신프로 보고 혼자 못자는 아들 어떡하죠? 하ㅜㅜ,2026.05.21. 23:45,중1이에요\n학교에서 선생님이\n귀신나오는 프로그램을 틀어주셔서\n애들이 봤대요\n...,[오늘 뭐 먹지] ㅠㅠㅠ 저도 중1때 공포영화보고 무서워서 힘들었어요..\n잘때 불...,귀신프로 보고 혼자 못자는 아들 어떡하죠? 하ㅜㅜ 중1이에요\n학교에서 선생님이\n...

# 중복글 확인 및 제거 -> 확인해보니 중복 없네

In [ ]:
# 중복 검사 기준 열
dup_subset = ['제목', '날짜', '본문']

# 중복된 모든 행(원본 포함)을 찾아서 필터링
# keep=False 옵션을 주면 중복된 쌍(세트) 전체를 모두 띄워줍니다.
duplicated_rows = df[df.duplicated(subset=dup_subset, keep=False)]

# 눈으로 확인하기 쉽게 제목과 날짜순으로 정렬
duplicated_rows = duplicated_rows.sort_values(by=['제목', '날짜'])

# 중복 데이터가 총 몇 개인지 확인
print(f"중복된 전체 행 개수: {len(duplicated_rows)}개")

# 중복된 데이터 직접 출력해서 보기 (전체 열 확인)
print(duplicated_rows[dup_subset])

중복된 전체 행 개수: 0개
Empty DataFrame
Columns: [제목, 날짜, 본문]
Index: []

In [ ]:
# 중복을 검사할 기준 열 지정
dup_subset = ['제목', '날짜', '본문']

# 지정한 열들을 기준으로 중복 데이터 제거 (첫 번째 행만 유지)
df = df.drop_duplicates(subset=dup_subset, keep='first')

# 중복 제거 후 빈 인덱스를 깔끔하게 재정렬
df = df.reset_index(drop=True)

# 결과 확인
df

,검색어,제목,날짜,본문,댓글,통합본문
0,층간소음,층간소음 방지 매트 언제까지 깔아놓으세요?,2026.05.22. 13:19,첫째가 돌무렵부터 깔아놓은 층간소음매트\n지금 그 애가 11살이에요.남자아이라 활동...,[me before U] 둘째 8살까지는...\n[대댓글시비충극혐] 애가 둘이면 더...,층간소음 방지 매트 언제까지 깔아놓으세요? 첫째가 돌무렵부터 깔아놓은 층간소음매트\...
1,층간소음,층간소음은 어디까지 이해해야 하나요?,2026.05.21. 22:48,윗층에 유치원 다니는 쌍둥이들이 살아요\n처음에 이사왔을때 너무 뛰어다니길래\n한번...,[두쫑크] 층간소음은 참으면 계속 참아야 합니다..\n[더 멋진 오늘] 그럼 참지 ...,층간소음은 어디까지 이해해야 하나요? 윗층에 유치원 다니는 쌍둥이들이 살아요\n처음...
2,층간소음,변비 있는분들 운동 해보세요,2026.05.21. 17:01,요구르트 먹어요 겨우겨우였는데 장이 흔들릴 정도의 댄스를 하니까 그냥 거의 매일 입...,[alclsshadk] 5키로씩 러닝 뛰었을 때 장은 안 변하던데요........ㅜ...,변비 있는분들 운동 해보세요 요구르트 먹어요 겨우겨우였는데 장이 흔들릴 정도의 댄스...
3,층간소음,층간소음 발망치...가서 얘기해도 될까요..ㅜ,2026.05.21. 14:05,10년동안 살면서 윗집복은 있었는데..\n이번에 윗집 새로 이사오고 층간소음이 시달...,[복슝야] 발망치 소리는 얘기해야죠\n[반짝이핑쿠핑쿠] 네..온갖상상회로 올리는데 ...,층간소음 발망치...가서 얘기해도 될까요..ㅜ 10년동안 살면서 윗집복은 있었는데....
4,층간소음,층간소음 실내화,2026.05.21. 12:54,윗층 노부부 사시는데요\n좋으신분들이에요 오며가며 인사도 하구요\n명절때 너무 시끄...,[고랴니] 기분 나빠할거 같긴 해요,층간소음 실내화 윗층 노부부 사시는데요\n좋으신분들이에요 오며가며 인사도 하구요\n...
...,...,...,...,...,...,...
2033,화장실,물탱크 청소중.화장실 가고싶네요😂,2026.05.22. 09:56,물탱크 청소중이라 물잠궈놔서 새벽부터 물이 안나와요.\n세탁기에 물받아놔서 쓰긴한데...,[또순이좋아] 아파트가 아니라서 상가가 없어요ㅜㅜ,물탱크 청소중.화장실 가고싶네요😂 물탱크 청소중이라 물잠궈놔서 새벽부터 물이 안나와...
2034,화장실,증상:쓰러질것같을때 대변보면 괜찮아지는느낌????,2026.05.22. 09:26,어디 물어보기 애매하고 민망해서 글올려봅니다\n집안일하고 있는평범한 날이였는데요\n...,[숑이1] 그거 미주신경성실신이요 ㅜㅜ 저도 그래요\n[긍정님0] 그럼 따로 약을 ...,증상:쓰러질것같을때 대변보면 괜찮아지는느낌???? 어디 물어보기 애매하고 민망해서 ...
2035,화장실,"화장실에 욕실화,몇개세요?",2026.05.22. 09:22,저흰 발사이즈 250과 290이 같이 쓰는 욕실예요.\n문앞에 두개씩 놓자니 번잡하...,[내 얘기 금지] 큰사이즈로 하나만 둬요 화장실에서 잠깐 쓰는건데요\n[jivaka...,"화장실에 욕실화,몇개세요? 저흰 발사이즈 250과 290이 같이 쓰는 욕실예요.\n..."
2036,화장실,런닝하시는 분들 무릎 살짝?아파도 뛰시나요.?,2026.05.22. 07:07,"며질전부터 무릎이 마구 아프다기보단,\n무릎 굽힐때 아픈 느낌? 불편한 느낌이 있어...",[호반영] 아이구야 안되요 빨리병원가봐요\n엄청오래가던데요 무릎ㅠㅠ\n[반짝이는 메...,"런닝하시는 분들 무릎 살짝?아파도 뛰시나요.? 며질전부터 무릎이 마구 아프다기보단,..."
2037,화장실,귀신프로 보고 혼자 못자는 아들 어떡하죠? 하ㅜㅜ,2026.05.21. 23:45,중1이에요\n학교에서 선생님이\n귀신나오는 프로그램을 틀어주셔서\n애들이 봤대요\n...,[오늘 뭐 먹지] ㅠㅠㅠ 저도 중1때 공포영화보고 무서워서 힘들었어요..\n잘때 불...,귀신프로 보고 혼자 못자는 아들 어떡하죠? 하ㅜㅜ 중1이에요\n학교에서 선생님이\n...

# 동의어 유의어 처리

In [ ]:
import pandas as pd
import re


# 2. 추가 노이즈 단어 리스트 (알바, 견적, 정보요청 등)
EXTRA_NOISE_WORDS = ['알바', '견적', '정보좀주세요', '공유부탁', '쪽지주세요', '비댓', '비댓글']
noise_pattern = '|'.join(EXTRA_NOISE_WORDS)

# [실행] 노이즈 행 제거
before_len = len(df)
df = df[~df['통합본문'].str.contains(noise_pattern, na=False, case=False)]
print(f"✅ 노이즈 행 제거 완료: {before_len}개 -> {len(df)}개")

# 3. 동의어/유의어 사전 정의
synonym_dict = {

  # 소음 관련
    '층소': '층간소음', '층소충': '층간소음', '발망치': '층간소음', '쌩발망치소리': '층간소음',
    '쿵쾅': '층간소음', '쿵쾅쿵쾅': '층간소음', '쿵쿵': '층간소음', '쿵쾅거림': '층간소음',
    '우당탕': '층간소음', '우당탕탕': '층간소음', '우다다': '층간소음', '우다다다': '층간소음',

    # 이웃 지칭
    '위층': '윗집', '윗층': '윗집', '아래층': '아랫집', '밑에집': '아랫집',

    # 아이/연령 관련
    '애': '아이', '애기': '아이', '아기': '아이', '아가': '아이', '애들': '아이들', '꼬맹이': '아이들',
    '첫째': '아이', '둘째': '아이', '아들': '아이', '딸': '아이', '아들램': '아이',
    '초딩': '초등학생', '초등': '초등학생', '초1': '초등학생', '초2': '초등학생', '초3': '초등학생',
    '초4': '초등학생', '초5': '초등학생', '초6': '초등학생', '저학년': '초등학생', '고학년': '초등학생',
    '중딩': '중학생', '중1': '중학생', '중2': '중학생', '중3': '중학생',
    '고딩': '고등학생', '고1': '고등학생', '고3': '고등학생', '수험생': '고등학생',
    '노인': '어르신', '노부부': '어르신', '할머니': '어르신', '할배': '어르신',

    # 대처 및 해결책
    '관리실': '관리사무소', '관리소': '관리사무소', '관리사무실': '관리사무소', '방재실': '관리사무소',
    '경비실': '관리사무소', '경비': '관리사무소',
    '층간소음매트': '매트', '시공매트': '매트', '롤매트': '매트', '폴더매트': '매트', '퍼즐매트': '매트',
    '슬리퍼': '실내화', '덧신': '실내화', '층간소음슬리퍼': '실내화',

    # 상태/감정
    '노이로제': '스트레스', '빡침': '스트레스', '짜증': '스트레스', '분노': '스트레스', '환장': '스트레스',
    '귀트임': '소음민감', '귀 트임': '소음민감',

    # 주거 형태
    '아팟': '아파트'
층
}

# 동의어 치환 함수
def replace_synonyms(text):
    if not isinstance(text, str): return ""
    for key, value in synonym_dict.items():
        text = text.replace(key, value)
    return text

# [실행] 동의어 처리 진행
df['통합본문'] = df['통합본문'].apply(replace_synonyms)

# 4. 연속 공백 정리 (치환 후 발생한 공백 제거)
df['통합본문'] = df['통합본문'].str.replace(r'\s+', ' ', regex=True).str.strip()

print("✅ 동의어 및 유의어 통합 처리 완료!")

df.head(20)

✅ 노이즈 행 제거 완료: 2038개 -> 1999개

/tmp/ipykernel_1335/2859148960.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['통합본문'] = df['통합본문'].apply(replace_synonyms)

✅ 동의어 및 유의어 통합 처리 완료!

/tmp/ipykernel_1335/2859148960.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['통합본문'] = df['통합본문'].str.replace(r'\s+', ' ', regex=True).str.strip()

,검색어,제목,날짜,본문,댓글,통합본문
0,층간소음,층간소음 방지 매트 언제까지 깔아놓으세요?,2026.05.22. 13:19,첫째가 돌무렵부터 깔아놓은 층간소음매트\n지금 그 애가 11살이에요.남자아이라 활동...,[me before U] 둘째 8살까지는...\n[대댓글시비충극혐] 애가 둘이면 더...,층간소음 방지 매트 언제까지 깔아놓으세요? 아이가 돌무렵부터 깔아놓은 매트 지금 그...
1,층간소음,층간소음은 어디까지 이해해야 하나요?,2026.05.21. 22:48,윗층에 유치원 다니는 쌍둥이들이 살아요\n처음에 이사왔을때 너무 뛰어다니길래\n한번...,[두쫑크] 층간소음은 참으면 계속 참아야 합니다..\n[더 멋진 오늘] 그럼 참지 ...,층간소음은 어디까지 이해해야 하나요? 윗집에 유치원 다니는 쌍둥이들이 살아요 처음에...
2,층간소음,변비 있는분들 운동 해보세요,2026.05.21. 17:01,요구르트 먹어요 겨우겨우였는데 장이 흔들릴 정도의 댄스를 하니까 그냥 거의 매일 입...,[alclsshadk] 5키로씩 러닝 뛰었을 때 장은 안 변하던데요........ㅜ...,변비 있는분들 운동 해보세요 요구르트 먹어요 겨우겨우였는데 장이 흔들릴 정도의 댄스...
3,층간소음,층간소음 발망치...가서 얘기해도 될까요..ㅜ,2026.05.21. 14:05,10년동안 살면서 윗집복은 있었는데..\n이번에 윗집 새로 이사오고 층간소음이 시달...,[복슝야] 발망치 소리는 얘기해야죠\n[반짝이핑쿠핑쿠] 네..온갖상상회로 올리는데 ...,층간소음 층간소음...가서 얘기해도 될까요..ㅜ 10년동안 살면서 윗집복은 있었는데...
4,층간소음,층간소음 실내화,2026.05.21. 12:54,윗층 노부부 사시는데요\n좋으신분들이에요 오며가며 인사도 하구요\n명절때 너무 시끄...,[고랴니] 기분 나빠할거 같긴 해요,층간소음 실내화 윗집 어르신 사시는데요 좋으신분들이에요 오며가며 인사도 하구요 명절...
5,층간소음,층간소음 직접 말하면 안되죠?,2026.05.21. 07:01,위층집 이사오고부터 밤이고 낮이고 울리는 천장소리..\n새벽2시부터 5시까지 울린적...,[잘먹고잘노는남매맘] 관리소에 전달하세요. 그정도면 핸드폰으로 녹음해 놔도 될거같아...,층간소음 직접 말하면 안되죠? 윗집집 이사오고부터 밤이고 낮이고 울리는 천장소리.....
6,층간소음,배관에서 나는 소음을 층간소음으로 오해하고 살해된 아버지,2026.05.20. 20:05,"https://naver.me/GP2lNvsE\n""집 비운 날도 시끄럽다 항의""…'...",[뭣이라] 너무 슬픈일 이네요\n전에 제 아는분 사는집ㄷ\n아랫층 주민이\n정신질환...,배관에서 나는 소음을 층간소음으로 오해하고 살해된 아버지 https://naver....
7,층간소음,층간소음 때문에 인류애가 사라져요,2026.05.20. 17:13,3월부터 층간소음 시달려서\n관리사무소 통해서 상담하고 조정하고있어요.\n윗집은 그...,[니나니농] 아 층간소음 안겪어본사람은 모르죠 진짜 인간혐오생겨요\n[오늘의주인공은...,층간소음 때문에 인류아이가 사라져요 3월부터 층간소음 시달려서 관리사무소 통해서 상...
8,층간소음,층간소음때문에 이사가는 경우예요,2026.05.20. 06:24,말 안하면 나중에 문제생기나요???,[레몬트라이스] 말해주는집이없을걸요\n[화이트2] 2222222\n[뚜뚜이이] 층간...,층간소음때문에 이사가는 경우예요 말 안하면 나중에 문제생기나요??? [레몬트라이스]...
9,층간소음,누수 발생시 관리실,2026.05.19. 08:15,윗집으로 인해 누수가 발생했는데요\n발견한지 일주일 좀 넘었는데\n관리실에서 확인해...,[미쳐가나봄] 누수란게 윗집서 뭘 잠궜다고 금방 해결된 일이 아니예요.\n관리실말처...,누수 발생시 관리사무소 윗집으로 인해 누수가 발생했는데요 발견한지 일주일 좀 넘었는...
10,층간소음,층간소음매트 다소니매트 시공후기 !,2026.05.18. 14:29,친구 집 놀러갔다가 층간소음매트 다소니매트 시공한거 보고\n생각보다 너무 괜찮아서 ...,[설렘설렘해] 색감 깔끔한 매트 찾고 있었는데 다소니매트 괜찮아보이네요!\n[떡바라...,매트 다소니매트 시공후기 ! 친구 집 놀러갔다가 매트 다소니매트 시공한거 보고 생각...
11,층간소음,층간소음 보복으로 타이어 테러당했어요..너무 무서워요,2026.05.18. 09:34,"안녕하세요, 수원 망포동 소재 아파트 입주민이에요.\n작년 9월 입주 때부터 아래층...",[단무지김밥] 층간소음이 어느정도인지 몰라서 모르겠지만.. 타이어 펑크내는건 싸이코...,"층간소음 보복으로 타이어 테러당했어요..너무 무서워요 안녕하세요, 수원 망포동 소재..."
12,층간소음,대형평수로 갈아타고싶어요....,2026.05.18. 00:20,애들도 각자의 공간이 필요하고 짐도많아지고 ...넓은평수가고 싶어요 (30평후반40...,[문해력키우고댓글써라] 후회함요 걍계세요ㅠ\n[민쵸럽] 네 댓글 감사합니다\n[인류...,대형평수로 갈아타고싶어요.... 아이들도 각자의 공간이 필요하고 짐도많아지고 ......
13,층간소음,(층간소음) 대체 장독대 끄는 소리랑 무거운거 떨어트리는 소리는 왜 나요???,2026.05.17. 20:44,"윗집에서 주말마다 대청소를 하는 거 같은데요\n가구끄는소리,청소기미는 소리랑 발망치...",[dhfl2177] 옛날 저희 윗집이랑 똑같아요 진심 가끔 꽝!!!! 소리에 진짜 ...,(층간소음) 대체 장독대 끄는 소리랑 무거운거 떨어트리는 소리는 왜 나요??? 윗집...
14,층간소음,층간소음의 암묵적 합의?,2026.05.17. 02:01,저희 집은 1층이에요\n다자녀집입니다.\n소리가 위로 올라간다고해서 밤 늦은 시간은...,[직감대로] 아니 너무 현명하시고 긍정적이시네욬ㅋㅋㅋㅋㅋㅋ 아 정말 유쾌한 글입니닼...,층간소음의 암묵적 합의? 저희 집은 1층이에요 다자녀집입니다. 소리가 위로 올라간다...
15,층간소음,창문형 에어컨 소음 올해도 시작이네요..,2026.05.16. 23:43,웅웅웅 거리는 특유의 저주파 소음\n듣고 있으면 주기적인 웅웅 소리 때문에\n토할 ...,[찐 채크아웃중] 정말 토할 것 같고 눈물이나요 ㅠㅠ\n더워서 지집에서 에어컨 튼다...,창문형 에어컨 소음 올해도 시작이네요.. 웅웅웅 거리는 특유의 저주파 소음 듣고 있...
16,층간소음,층간소음 관련 문의드려요~,2026.05.16. 19:20,"로봇청소기, 자전거 운동기구, 물걸레 로봇 청소기(에브리봇), 무선 물걸레 청소기,...",[육아파이터] 로봇청소기가 소음이 있나요?\n전혀 모르겠는데\n[나플나플나비] 로봇...,"층간소음 관련 문의드려요~ 로봇청소기, 자전거 운동기구, 물걸레 로봇 청소기(에브리..."
17,층간소음,층간소음 있는 분들 생활 어떻게 하세요,2026.05.15. 17:54,집에서 쉴틈없이 소음에 시달리는 분들 일상생활 어떻게\n하세요\n익숙해져서 그냥그냥...,[alebrije] 그냥 참았어요.그냥\n헤드셋 끼고 음악듣고\n유튭보고\n[for...,층간소음 있는 분들 생활 어떻게 하세요 집에서 쉴틈없이 소음에 시달리는 분들 일상생...
19,층간소음,요즘 뭐가 그리 사고싶으세요?,2026.05.15. 09:56,저는 귀걸이랑 원피스요^^,"[두통유발자] 전기차?\n[내가너의손자봐줄게] 차를 새로 사서, 차 꾸미는 용품요 ...",요즘 뭐가 그리 사고싶으세요? 저는 귀걸이랑 원피스요^^ [두통유발자] 전기차? [...
20,층간소음,김치냉장고에서 돌이나 구슬 떨어지는소리,2026.05.14. 20:18,제목그대로 저 소리가 나서\n서비스센타 전화해보니\n뒷쪽 하단 냉각시스템이 작동하다...,,김치냉장고에서 돌이나 구슬 떨어지는소리 제목그대로 저 소리가 나서 서비스센타 전화해...

# 대소문자 통일

In [ ]:
df["통합본문"] = df["통합본문"].apply(lambda x : x.lower())
df

/tmp/ipykernel_1335/3129417404.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["통합본문"] = df["통합본문"].apply(lambda x : x.lower())

,검색어,제목,날짜,본문,댓글,통합본문
0,층간소음,층간소음 방지 매트 언제까지 깔아놓으세요?,2026.05.22. 13:19,첫째가 돌무렵부터 깔아놓은 층간소음매트\n지금 그 애가 11살이에요.남자아이라 활동...,[me before U] 둘째 8살까지는...\n[대댓글시비충극혐] 애가 둘이면 더...,층간소음 방지 매트 언제까지 깔아놓으세요? 아이가 돌무렵부터 깔아놓은 매트 지금 그...
1,층간소음,층간소음은 어디까지 이해해야 하나요?,2026.05.21. 22:48,윗층에 유치원 다니는 쌍둥이들이 살아요\n처음에 이사왔을때 너무 뛰어다니길래\n한번...,[두쫑크] 층간소음은 참으면 계속 참아야 합니다..\n[더 멋진 오늘] 그럼 참지 ...,층간소음은 어디까지 이해해야 하나요? 윗집에 유치원 다니는 쌍둥이들이 살아요 처음에...
2,층간소음,변비 있는분들 운동 해보세요,2026.05.21. 17:01,요구르트 먹어요 겨우겨우였는데 장이 흔들릴 정도의 댄스를 하니까 그냥 거의 매일 입...,[alclsshadk] 5키로씩 러닝 뛰었을 때 장은 안 변하던데요........ㅜ...,변비 있는분들 운동 해보세요 요구르트 먹어요 겨우겨우였는데 장이 흔들릴 정도의 댄스...
3,층간소음,층간소음 발망치...가서 얘기해도 될까요..ㅜ,2026.05.21. 14:05,10년동안 살면서 윗집복은 있었는데..\n이번에 윗집 새로 이사오고 층간소음이 시달...,[복슝야] 발망치 소리는 얘기해야죠\n[반짝이핑쿠핑쿠] 네..온갖상상회로 올리는데 ...,층간소음 층간소음...가서 얘기해도 될까요..ㅜ 10년동안 살면서 윗집복은 있었는데...
4,층간소음,층간소음 실내화,2026.05.21. 12:54,윗층 노부부 사시는데요\n좋으신분들이에요 오며가며 인사도 하구요\n명절때 너무 시끄...,[고랴니] 기분 나빠할거 같긴 해요,층간소음 실내화 윗집 어르신 사시는데요 좋으신분들이에요 오며가며 인사도 하구요 명절...
...,...,...,...,...,...,...
2032,화장실,변비 심하신 분들요..,2026.05.22. 11:36,토마토 쥬스 만들어서 냉장고에 넣고 시원하게 드셔보세요..\n꿀 넣고 달달하게 갈아...,[옐로우프린세스] 오 나중에 먹어봐야겠어요\n[마리yj] 토마토도 변비에 좋은가보네...,변비 심하신 분들요.. 토마토 쥬스 만들어서 냉장고에 넣고 시원하게 드셔보세요.. ...
2033,화장실,물탱크 청소중.화장실 가고싶네요😂,2026.05.22. 09:56,물탱크 청소중이라 물잠궈놔서 새벽부터 물이 안나와요.\n세탁기에 물받아놔서 쓰긴한데...,[또순이좋아] 아파트가 아니라서 상가가 없어요ㅜㅜ,물탱크 청소중.화장실 가고싶네요😂 물탱크 청소중이라 물잠궈놔서 새벽부터 물이 안나와...
2034,화장실,증상:쓰러질것같을때 대변보면 괜찮아지는느낌????,2026.05.22. 09:26,어디 물어보기 애매하고 민망해서 글올려봅니다\n집안일하고 있는평범한 날이였는데요\n...,[숑이1] 그거 미주신경성실신이요 ㅜㅜ 저도 그래요\n[긍정님0] 그럼 따로 약을 ...,증상:쓰러질것같을때 대변보면 괜찮아지는느낌???? 어디 물어보기 아이매하고 민망해서...
2035,화장실,"화장실에 욕실화,몇개세요?",2026.05.22. 09:22,저흰 발사이즈 250과 290이 같이 쓰는 욕실예요.\n문앞에 두개씩 놓자니 번잡하...,[내 얘기 금지] 큰사이즈로 하나만 둬요 화장실에서 잠깐 쓰는건데요\n[jivaka...,"화장실에 욕실화,몇개세요? 저흰 발사이즈 250과 290이 같이 쓰는 욕실예요. 문..."
2036,화장실,런닝하시는 분들 무릎 살짝?아파도 뛰시나요.?,2026.05.22. 07:07,"며질전부터 무릎이 마구 아프다기보단,\n무릎 굽힐때 아픈 느낌? 불편한 느낌이 있어...",[호반영] 아이구야 안되요 빨리병원가봐요\n엄청오래가던데요 무릎ㅠㅠ\n[반짝이는 메...,"런닝하시는 분들 무릎 살짝?아파도 뛰시나요.? 며질전부터 무릎이 마구 아프다기보단,..."

#노이즈 제거

In [ ]:
# 2. 추가 노이즈 단어 리스트 (알바, 견적, 정보요청 등)
EXTRA_NOISE_WORDS = ['알바', '견적', '정보좀주세요', '공유부탁', '쪽지주세요', '비댓', '비댓글', '관상', '기아', '야구', '채용', '장투', '한화오션', '팬션','마스크',
                     '단가하락', '강원도', '빌라', '풀옵션', '동유럽', '패키지','미장','환율','오픈합니다','아파트','스푼라디오','법인택시', '김빈우', '발사이즈','변비','화장실']
noise_pattern = '|'.join(EXTRA_NOISE_WORDS)

# [실행] 노이즈 행 제거
before_len = len(df)
df = df[~df['통합본문'].str.contains(noise_pattern, na=False, case=False)]

In [ ]:
df

,검색어,제목,날짜,본문,댓글,통합본문
0,층간소음,층간소음 방지 매트 언제까지 깔아놓으세요?,2026.05.22. 13:19,첫째가 돌무렵부터 깔아놓은 층간소음매트\n지금 그 애가 11살이에요.남자아이라 활동...,[me before U] 둘째 8살까지는...\n[대댓글시비충극혐] 애가 둘이면 더...,층간소음 방지 매트 언제까지 깔아놓으세요? 아이가 돌무렵부터 깔아놓은 매트 지금 그...
4,층간소음,층간소음 실내화,2026.05.21. 12:54,윗층 노부부 사시는데요\n좋으신분들이에요 오며가며 인사도 하구요\n명절때 너무 시끄...,[고랴니] 기분 나빠할거 같긴 해요,층간소음 실내화 윗집 어르신 사시는데요 좋으신분들이에요 오며가며 인사도 하구요 명절...
5,층간소음,층간소음 직접 말하면 안되죠?,2026.05.21. 07:01,위층집 이사오고부터 밤이고 낮이고 울리는 천장소리..\n새벽2시부터 5시까지 울린적...,[잘먹고잘노는남매맘] 관리소에 전달하세요. 그정도면 핸드폰으로 녹음해 놔도 될거같아...,층간소음 직접 말하면 안되죠? 윗집집 이사오고부터 밤이고 낮이고 울리는 천장소리.....
8,층간소음,층간소음때문에 이사가는 경우예요,2026.05.20. 06:24,말 안하면 나중에 문제생기나요???,[레몬트라이스] 말해주는집이없을걸요\n[화이트2] 2222222\n[뚜뚜이이] 층간...,층간소음때문에 이사가는 경우예요 말 안하면 나중에 문제생기나요??? [레몬트라이스]...
9,층간소음,누수 발생시 관리실,2026.05.19. 08:15,윗집으로 인해 누수가 발생했는데요\n발견한지 일주일 좀 넘었는데\n관리실에서 확인해...,[미쳐가나봄] 누수란게 윗집서 뭘 잠궜다고 금방 해결된 일이 아니예요.\n관리실말처...,누수 발생시 관리사무소 윗집으로 인해 누수가 발생했는데요 발견한지 일주일 좀 넘었는...
...,...,...,...,...,...,...
2006,발망치,슬리퍼신어도 층간소음,2024.12.17. 09:54,날까요? 대각선집에서 발망치소리가 난다고 문자가와서너무스트레스네요,[이네] 슬리퍼 신어도 발망치소리 나요ㅜㅜ\n[Kangar00] 아이고 그럼 어떻게...,실내화신어도 층간소음 날까요? 대각선집에서 층간소음소리가 난다고 문자가와서너무스트레...
2010,발망치,층간소음 기준,2024.12.15. 22:04,층간소음 어디까지 이해해주시나요?,[꼼꼼해용] 네 그럴게요 댓글 감사해요\n[꼼꼼해용] 네 감사해요 좋은 밤 되세요\...,층간소음 기준 층간소음 어디까지 이해해주시나요? [꼼꼼해용] 네 그럴게요 댓글 감사...
2013,발망치,천장치면 윗집에 들리나요???,2024.12.09. 23:54,층간소음으로 매일 수십번 부수고 싶은 충동이..\n천정치면 윗집에 들릴까요?,[찰옥듀듀] 몰딩이 어디에요??\n[햇빛모자] 아주잘들립니다 주말낮에 청소기만밀어도...,천장치면 윗집에 들리나요??? 층간소음으로 매일 수십번 부수고 싶은 충동이.. 천정...
2015,발망치,강아지 방치하면 학대아닌가요?,2024.12.04. 01:31,윗집 이사오고부터\n강아지 짖는 소리에 며칠째 잠을 못자는데\n인터폰도 안받고\n관...,[힐버] 전 요즘 혼자사는 사람들이 많아서 사고도 걱정되드라구요 ㅠ 혹시 무슨일 생...,강아지 방치하면 학대아닌가요? 윗집 이사오고부터 강아지 짖는 소리에 며칠째 잠을 못...
2018,발망치,안마기 소리에 깼어요,2024.12.01. 05:59,징글징글 합니다 ㅜㅜ,[포테이토는 맛있지] ㅜㅜ 네\n[하하하요용] 안마기 소린진 런닝머신 소린지 규칙적...,안마기 소리에 깼어요 징글징글 합니다 ㅜㅜ [포테이토는 맛있지] ㅜㅜ 네 [하하하요...

# 특수문자 및 이모지 제거

In [ ]:
import re

# 1. 한글(가-힣), 영문(a-zA-Z), 숫자(0-9), 공백(\s)을 제외한 모든 문자를 공백(' ')으로 대체
# 특수문자가 있던 자리를 띄어쓰기로 바꿔주어 단어들이 달라붙는 것을 방지합니다. (예: "층간소음/스트레스" -> "층간소음 스트레스")
df['통합본문'] = df['통합본문'].str.replace(r'[^가-힣a-zA-Z0-9\s]', ' ', regex=True)

# 2. ㅋㅋ, ㅎㅎ, ㅠㅠ 같은 단일 자음/모음도 노이즈가 될 수 있으므로 제거 (선택 사항)
df['통합본문'] = df['통합본문'].str.replace(r'[ㄱ-ㅎㅏ-ㅣ]', ' ', regex=True)

# 3. 특수문자가 공백으로 변환되면서 생긴 2개 이상의 연속된 공백을 하나로 줄이기
df['통합본문'] = df['통합본문'].str.replace(r'\s+', ' ', regex=True)

# 4. 문자열 양쪽 끝에 남아있는 공백 제거
df['통합본문'] = df['통합본문'].str.strip()
df

,검색어,제목,날짜,본문,댓글,통합본문,통합본문_정제
0,층간소음,층간소음 방지 매트 언제까지 깔아놓으세요?,2026.05.22. 13:19,첫째가 돌무렵부터 깔아놓은 층간소음매트\n지금 그 애가 11살이에요.남자아이라 활동...,[me before U] 둘째 8살까지는...\n[대댓글시비충극혐] 애가 둘이면 더...,층간소음 방지 매트 언제까지 깔아놓으세요 아이가 돌무렵부터 깔아놓은 매트 지금 그 ...,층간소음 방지 매트 언제까지 깔아놓으세요 아이가 돌무렵부터 깔아놓은 매트 지금 그 ...
4,층간소음,층간소음 실내화,2026.05.21. 12:54,윗층 노부부 사시는데요\n좋으신분들이에요 오며가며 인사도 하구요\n명절때 너무 시끄...,[고랴니] 기분 나빠할거 같긴 해요,층간소음 실내화 윗집 어르신 사시는데요 좋으신분들이에요 오며가며 인사도 하구요 명절...,층간소음 실내화 윗집 어르신 사시는데요 좋으신분들이에요 오며가며 인사도 하구요 명절...
5,층간소음,층간소음 직접 말하면 안되죠?,2026.05.21. 07:01,위층집 이사오고부터 밤이고 낮이고 울리는 천장소리..\n새벽2시부터 5시까지 울린적...,[잘먹고잘노는남매맘] 관리소에 전달하세요. 그정도면 핸드폰으로 녹음해 놔도 될거같아...,층간소음 직접 말하면 안되죠 윗집집 이사오고부터 밤이고 낮이고 울리는 천장소리 새벽...,층간소음 직접 말하면 안되죠 윗집집 이사오고부터 밤이고 낮이고 울리는 천장소리 새벽...
8,층간소음,층간소음때문에 이사가는 경우예요,2026.05.20. 06:24,말 안하면 나중에 문제생기나요???,[레몬트라이스] 말해주는집이없을걸요\n[화이트2] 2222222\n[뚜뚜이이] 층간...,층간소음때문에 이사가는 경우예요 말 안하면 나중에 문제생기나요 레몬트라이스 말해주는...,층간소음때문에 이사가는 경우예요 말 안하면 나중에 문제생기나요 레몬트라이스 말해주는...
9,층간소음,누수 발생시 관리실,2026.05.19. 08:15,윗집으로 인해 누수가 발생했는데요\n발견한지 일주일 좀 넘었는데\n관리실에서 확인해...,[미쳐가나봄] 누수란게 윗집서 뭘 잠궜다고 금방 해결된 일이 아니예요.\n관리실말처...,누수 발생시 관리사무소 윗집으로 인해 누수가 발생했는데요 발견한지 일주일 좀 넘었는...,누수 발생시 관리사무소 윗집으로 인해 누수가 발생했는데요 발견한지 일주일 좀 넘었는...
...,...,...,...,...,...,...,...
2006,발망치,슬리퍼신어도 층간소음,2024.12.17. 09:54,날까요? 대각선집에서 발망치소리가 난다고 문자가와서너무스트레스네요,[이네] 슬리퍼 신어도 발망치소리 나요ㅜㅜ\n[Kangar00] 아이고 그럼 어떻게...,실내화신어도 층간소음 날까요 대각선집에서 층간소음소리가 난다고 문자가와서너무스트레스...,실내화신어도 층간소음 날까요 대각선집에서 층간소음소리가 난다고 문자가와서너무스트레스...
2010,발망치,층간소음 기준,2024.12.15. 22:04,층간소음 어디까지 이해해주시나요?,[꼼꼼해용] 네 그럴게요 댓글 감사해요\n[꼼꼼해용] 네 감사해요 좋은 밤 되세요\...,층간소음 기준 층간소음 어디까지 이해해주시나요 꼼꼼해용 네 그럴게요 댓글 감사해요 ...,층간소음 기준 층간소음 어디까지 이해해주시나요 꼼꼼해용 네 그럴게요 댓글 감사해요 ...
2013,발망치,천장치면 윗집에 들리나요???,2024.12.09. 23:54,층간소음으로 매일 수십번 부수고 싶은 충동이..\n천정치면 윗집에 들릴까요?,[찰옥듀듀] 몰딩이 어디에요??\n[햇빛모자] 아주잘들립니다 주말낮에 청소기만밀어도...,천장치면 윗집에 들리나요 층간소음으로 매일 수십번 부수고 싶은 충동이 천정치면 윗집...,천장치면 윗집에 들리나요 층간소음으로 매일 수십번 부수고 싶은 충동이 천정치면 윗집...
2015,발망치,강아지 방치하면 학대아닌가요?,2024.12.04. 01:31,윗집 이사오고부터\n강아지 짖는 소리에 며칠째 잠을 못자는데\n인터폰도 안받고\n관...,[힐버] 전 요즘 혼자사는 사람들이 많아서 사고도 걱정되드라구요 ㅠ 혹시 무슨일 생...,강아지 방치하면 학대아닌가요 윗집 이사오고부터 강아지 짖는 소리에 며칠째 잠을 못자...,강아지 방치하면 학대아닌가요 윗집 이사오고부터 강아지 짖는 소리에 며칠째 잠을 못자...
2018,발망치,안마기 소리에 깼어요,2024.12.01. 05:59,징글징글 합니다 ㅜㅜ,[포테이토는 맛있지] ㅜㅜ 네\n[하하하요용] 안마기 소린진 런닝머신 소린지 규칙적...,안마기 소리에 깼어요 징글징글 합니다 포테이토는 맛있지 네 하하하요용 안마기 소린진...,안마기 소리에 깼어요 징글징글 합니다 포테이토는 맛있지 네 하하하요용 안마기 소린진...

In [ ]:
# '통합본문_정제' 열 삭제
df = df.drop(columns=['통합본문_정제'])

df

,검색어,제목,날짜,본문,댓글,통합본문
0,층간소음,층간소음 방지 매트 언제까지 깔아놓으세요?,2026.05.22. 13:19,첫째가 돌무렵부터 깔아놓은 층간소음매트\n지금 그 애가 11살이에요.남자아이라 활동...,[me before U] 둘째 8살까지는...\n[대댓글시비충극혐] 애가 둘이면 더...,층간소음 방지 매트 언제까지 깔아놓으세요 아이가 돌무렵부터 깔아놓은 매트 지금 그 ...
4,층간소음,층간소음 실내화,2026.05.21. 12:54,윗층 노부부 사시는데요\n좋으신분들이에요 오며가며 인사도 하구요\n명절때 너무 시끄...,[고랴니] 기분 나빠할거 같긴 해요,층간소음 실내화 윗집 어르신 사시는데요 좋으신분들이에요 오며가며 인사도 하구요 명절...
5,층간소음,층간소음 직접 말하면 안되죠?,2026.05.21. 07:01,위층집 이사오고부터 밤이고 낮이고 울리는 천장소리..\n새벽2시부터 5시까지 울린적...,[잘먹고잘노는남매맘] 관리소에 전달하세요. 그정도면 핸드폰으로 녹음해 놔도 될거같아...,층간소음 직접 말하면 안되죠 윗집집 이사오고부터 밤이고 낮이고 울리는 천장소리 새벽...
8,층간소음,층간소음때문에 이사가는 경우예요,2026.05.20. 06:24,말 안하면 나중에 문제생기나요???,[레몬트라이스] 말해주는집이없을걸요\n[화이트2] 2222222\n[뚜뚜이이] 층간...,층간소음때문에 이사가는 경우예요 말 안하면 나중에 문제생기나요 레몬트라이스 말해주는...
9,층간소음,누수 발생시 관리실,2026.05.19. 08:15,윗집으로 인해 누수가 발생했는데요\n발견한지 일주일 좀 넘었는데\n관리실에서 확인해...,[미쳐가나봄] 누수란게 윗집서 뭘 잠궜다고 금방 해결된 일이 아니예요.\n관리실말처...,누수 발생시 관리사무소 윗집으로 인해 누수가 발생했는데요 발견한지 일주일 좀 넘었는...
...,...,...,...,...,...,...
2006,발망치,슬리퍼신어도 층간소음,2024.12.17. 09:54,날까요? 대각선집에서 발망치소리가 난다고 문자가와서너무스트레스네요,[이네] 슬리퍼 신어도 발망치소리 나요ㅜㅜ\n[Kangar00] 아이고 그럼 어떻게...,실내화신어도 층간소음 날까요 대각선집에서 층간소음소리가 난다고 문자가와서너무스트레스...
2010,발망치,층간소음 기준,2024.12.15. 22:04,층간소음 어디까지 이해해주시나요?,[꼼꼼해용] 네 그럴게요 댓글 감사해요\n[꼼꼼해용] 네 감사해요 좋은 밤 되세요\...,층간소음 기준 층간소음 어디까지 이해해주시나요 꼼꼼해용 네 그럴게요 댓글 감사해요 ...
2013,발망치,천장치면 윗집에 들리나요???,2024.12.09. 23:54,층간소음으로 매일 수십번 부수고 싶은 충동이..\n천정치면 윗집에 들릴까요?,[찰옥듀듀] 몰딩이 어디에요??\n[햇빛모자] 아주잘들립니다 주말낮에 청소기만밀어도...,천장치면 윗집에 들리나요 층간소음으로 매일 수십번 부수고 싶은 충동이 천정치면 윗집...
2015,발망치,강아지 방치하면 학대아닌가요?,2024.12.04. 01:31,윗집 이사오고부터\n강아지 짖는 소리에 며칠째 잠을 못자는데\n인터폰도 안받고\n관...,[힐버] 전 요즘 혼자사는 사람들이 많아서 사고도 걱정되드라구요 ㅠ 혹시 무슨일 생...,강아지 방치하면 학대아닌가요 윗집 이사오고부터 강아지 짖는 소리에 며칠째 잠을 못자...
2018,발망치,안마기 소리에 깼어요,2024.12.01. 05:59,징글징글 합니다 ㅜㅜ,[포테이토는 맛있지] ㅜㅜ 네\n[하하하요용] 안마기 소린진 런닝머신 소린지 규칙적...,안마기 소리에 깼어요 징글징글 합니다 포테이토는 맛있지 네 하하하요용 안마기 소린진...

#토크나이징

In [ ]:
okt = Okt()
df["token"] = df["통합본문"].apply(lambda x : okt.morphs(x, stem = True, norm = True))
df

,검색어,제목,날짜,본문,댓글,통합본문,token
0,층간소음,층간소음 방지 매트 언제까지 깔아놓으세요?,2026.05.22. 13:19,첫째가 돌무렵부터 깔아놓은 층간소음매트\n지금 그 애가 11살이에요.남자아이라 활동...,[me before U] 둘째 8살까지는...\n[대댓글시비충극혐] 애가 둘이면 더...,층간소음 방지 매트 언제까지 깔아놓으세요 아이가 돌무렵부터 깔아놓은 매트 지금 그 ...,"[층간소음, 방지, 매트, 언제, 까지, 깔다, 아이, 가, 돌, 무렵, 부터, 깔..."
4,층간소음,층간소음 실내화,2026.05.21. 12:54,윗층 노부부 사시는데요\n좋으신분들이에요 오며가며 인사도 하구요\n명절때 너무 시끄...,[고랴니] 기분 나빠할거 같긴 해요,층간소음 실내화 윗집 어르신 사시는데요 좋으신분들이에요 오며가며 인사도 하구요 명절...,"[층간소음, 실내, 화, 윗, 집, 어르신, 사다, 좋다, 신분, 들, 이에요, 오..."
5,층간소음,층간소음 직접 말하면 안되죠?,2026.05.21. 07:01,위층집 이사오고부터 밤이고 낮이고 울리는 천장소리..\n새벽2시부터 5시까지 울린적...,[잘먹고잘노는남매맘] 관리소에 전달하세요. 그정도면 핸드폰으로 녹음해 놔도 될거같아...,층간소음 직접 말하면 안되죠 윗집집 이사오고부터 밤이고 낮이고 울리는 천장소리 새벽...,"[층간소음, 직접, 말, 하다, 안되다, 윗, 집집, 이, 사오, 고, 부터, 밤,..."
8,층간소음,층간소음때문에 이사가는 경우예요,2026.05.20. 06:24,말 안하면 나중에 문제생기나요???,[레몬트라이스] 말해주는집이없을걸요\n[화이트2] 2222222\n[뚜뚜이이] 층간...,층간소음때문에 이사가는 경우예요 말 안하면 나중에 문제생기나요 레몬트라이스 말해주는...,"[층간소음, 때문, 에, 이, 사가, 는, 경우, 예요, 말, 안, 하다, 나중, ..."
9,층간소음,누수 발생시 관리실,2026.05.19. 08:15,윗집으로 인해 누수가 발생했는데요\n발견한지 일주일 좀 넘었는데\n관리실에서 확인해...,[미쳐가나봄] 누수란게 윗집서 뭘 잠궜다고 금방 해결된 일이 아니예요.\n관리실말처...,누수 발생시 관리사무소 윗집으로 인해 누수가 발생했는데요 발견한지 일주일 좀 넘었는...,"[누수, 발생, 시, 관리, 사무소, 윗, 집, 으로, 인하다, 누수, 가, 발생,..."
...,...,...,...,...,...,...,...
2006,발망치,슬리퍼신어도 층간소음,2024.12.17. 09:54,날까요? 대각선집에서 발망치소리가 난다고 문자가와서너무스트레스네요,[이네] 슬리퍼 신어도 발망치소리 나요ㅜㅜ\n[Kangar00] 아이고 그럼 어떻게...,실내화신어도 층간소음 날까요 대각선집에서 층간소음소리가 난다고 문자가와서너무스트레스...,"[실내, 화신, 어도, 층간소음, 날다, 요, 대, 각, 선집, 에서, 층간소음, ..."
2010,발망치,층간소음 기준,2024.12.15. 22:04,층간소음 어디까지 이해해주시나요?,[꼼꼼해용] 네 그럴게요 댓글 감사해요\n[꼼꼼해용] 네 감사해요 좋은 밤 되세요\...,층간소음 기준 층간소음 어디까지 이해해주시나요 꼼꼼해용 네 그럴게요 댓글 감사해요 ...,"[층간소음, 기준, 층간소음, 어디, 까지, 이해, 해주다, 꼼꼼하다, 네, 그렇다..."
2013,발망치,천장치면 윗집에 들리나요???,2024.12.09. 23:54,층간소음으로 매일 수십번 부수고 싶은 충동이..\n천정치면 윗집에 들릴까요?,[찰옥듀듀] 몰딩이 어디에요??\n[햇빛모자] 아주잘들립니다 주말낮에 청소기만밀어도...,천장치면 윗집에 들리나요 층간소음으로 매일 수십번 부수고 싶은 충동이 천정치면 윗집...,"[천, 장치, 면, 윗, 집, 에, 들리다, 층간소음, 으로, 매일, 수십, 번, ..."
2015,발망치,강아지 방치하면 학대아닌가요?,2024.12.04. 01:31,윗집 이사오고부터\n강아지 짖는 소리에 며칠째 잠을 못자는데\n인터폰도 안받고\n관...,[힐버] 전 요즘 혼자사는 사람들이 많아서 사고도 걱정되드라구요 ㅠ 혹시 무슨일 생...,강아지 방치하면 학대아닌가요 윗집 이사오고부터 강아지 짖는 소리에 며칠째 잠을 못자...,"[강아지, 방치, 하다, 학대, 아니다, 윗, 집, 이, 사오, 고, 부터, 강아지..."
2018,발망치,안마기 소리에 깼어요,2024.12.01. 05:59,징글징글 합니다 ㅜㅜ,[포테이토는 맛있지] ㅜㅜ 네\n[하하하요용] 안마기 소린진 런닝머신 소린지 규칙적...,안마기 소리에 깼어요 징글징글 합니다 포테이토는 맛있지 네 하하하요용 안마기 소린진...,"[안마, 기, 소리, 에, 깨다, 징글징글, 하다, 포테이토, 는, 맛있다, 네, ..."

In [ ]:
from tqdm import tqdm

okt = Okt()
tqdm.pandas()

def extract_pos(text, pos):
  left=[]
  for i in okt.pos(text,stem=True, norm =True):  # i 가 하나의 튜플 형성
    if i[1] in pos:   # 만약 i의 첫번째 원소가 명사 동사 형용사라면,
      left.append(i[0])
  return left

df["token"] = df["통합본문"].progress_apply(lambda x : extract_pos(x, ["Noun", "Verb", "Adjective"]))
df

100%|██████████| 1111/1111 [01:48<00:00, 10.21it/s]

,검색어,제목,날짜,본문,댓글,통합본문,token
0,층간소음,층간소음 방지 매트 언제까지 깔아놓으세요?,2026.05.22. 13:19,첫째가 돌무렵부터 깔아놓은 층간소음매트\n지금 그 애가 11살이에요.남자아이라 활동...,[me before U] 둘째 8살까지는...\n[대댓글시비충극혐] 애가 둘이면 더...,층간소음 방지 매트 언제까지 깔아놓으세요 아이가 돌무렵부터 깔아놓은 매트 지금 그 ...,"[층간소음, 방지, 매트, 언제, 깔다, 아이, 돌, 무렵, 깔다, 매트, 지금, ..."
4,층간소음,층간소음 실내화,2026.05.21. 12:54,윗층 노부부 사시는데요\n좋으신분들이에요 오며가며 인사도 하구요\n명절때 너무 시끄...,[고랴니] 기분 나빠할거 같긴 해요,층간소음 실내화 윗집 어르신 사시는데요 좋으신분들이에요 오며가며 인사도 하구요 명절...,"[층간소음, 실내, 집, 어르신, 사다, 좋다, 신분, 오다, 인사, 하다, 명절,..."
5,층간소음,층간소음 직접 말하면 안되죠?,2026.05.21. 07:01,위층집 이사오고부터 밤이고 낮이고 울리는 천장소리..\n새벽2시부터 5시까지 울린적...,[잘먹고잘노는남매맘] 관리소에 전달하세요. 그정도면 핸드폰으로 녹음해 놔도 될거같아...,층간소음 직접 말하면 안되죠 윗집집 이사오고부터 밤이고 낮이고 울리는 천장소리 새벽...,"[층간소음, 직접, 말, 하다, 안되다, 집집, 고, 밤, 낮, 울리다, 천장, 소..."
8,층간소음,층간소음때문에 이사가는 경우예요,2026.05.20. 06:24,말 안하면 나중에 문제생기나요???,[레몬트라이스] 말해주는집이없을걸요\n[화이트2] 2222222\n[뚜뚜이이] 층간...,층간소음때문에 이사가는 경우예요 말 안하면 나중에 문제생기나요 레몬트라이스 말해주는...,"[층간소음, 때문, 사가, 경우, 말, 하다, 나중, 문제, 생기다, 레몬, 트, ..."
9,층간소음,누수 발생시 관리실,2026.05.19. 08:15,윗집으로 인해 누수가 발생했는데요\n발견한지 일주일 좀 넘었는데\n관리실에서 확인해...,[미쳐가나봄] 누수란게 윗집서 뭘 잠궜다고 금방 해결된 일이 아니예요.\n관리실말처...,누수 발생시 관리사무소 윗집으로 인해 누수가 발생했는데요 발견한지 일주일 좀 넘었는...,"[누수, 발생, 시, 관리, 사무소, 집, 인하다, 누수, 발생, 하다, 발견, 한..."
...,...,...,...,...,...,...,...
2006,발망치,슬리퍼신어도 층간소음,2024.12.17. 09:54,날까요? 대각선집에서 발망치소리가 난다고 문자가와서너무스트레스네요,[이네] 슬리퍼 신어도 발망치소리 나요ㅜㅜ\n[Kangar00] 아이고 그럼 어떻게...,실내화신어도 층간소음 날까요 대각선집에서 층간소음소리가 난다고 문자가와서너무스트레스...,"[실내, 화신, 어도, 층간소음, 날다, 요, 선집, 층간소음, 소리, 나다, 자가..."
2010,발망치,층간소음 기준,2024.12.15. 22:04,층간소음 어디까지 이해해주시나요?,[꼼꼼해용] 네 그럴게요 댓글 감사해요\n[꼼꼼해용] 네 감사해요 좋은 밤 되세요\...,층간소음 기준 층간소음 어디까지 이해해주시나요 꼼꼼해용 네 그럴게요 댓글 감사해요 ...,"[층간소음, 기준, 층간소음, 어디, 이해, 해주다, 꼼꼼하다, 네, 그렇다, 댓글..."
2013,발망치,천장치면 윗집에 들리나요???,2024.12.09. 23:54,층간소음으로 매일 수십번 부수고 싶은 충동이..\n천정치면 윗집에 들릴까요?,[찰옥듀듀] 몰딩이 어디에요??\n[햇빛모자] 아주잘들립니다 주말낮에 청소기만밀어도...,천장치면 윗집에 들리나요 층간소음으로 매일 수십번 부수고 싶은 충동이 천정치면 윗집...,"[장치, 집, 들리다, 층간소음, 매일, 번, 부수, 싶다, 충, 동이, 정치면, ..."
2015,발망치,강아지 방치하면 학대아닌가요?,2024.12.04. 01:31,윗집 이사오고부터\n강아지 짖는 소리에 며칠째 잠을 못자는데\n인터폰도 안받고\n관...,[힐버] 전 요즘 혼자사는 사람들이 많아서 사고도 걱정되드라구요 ㅠ 혹시 무슨일 생...,강아지 방치하면 학대아닌가요 윗집 이사오고부터 강아지 짖는 소리에 며칠째 잠을 못자...,"[강아지, 방치, 하다, 학대, 아니다, 집, 고, 강아지, 짖다, 소리, 며칠, ..."
2018,발망치,안마기 소리에 깼어요,2024.12.01. 05:59,징글징글 합니다 ㅜㅜ,[포테이토는 맛있지] ㅜㅜ 네\n[하하하요용] 안마기 소린진 런닝머신 소린지 규칙적...,안마기 소리에 깼어요 징글징글 합니다 포테이토는 맛있지 네 하하하요용 안마기 소린진...,"[안마, 기, 소리, 깨다, 징글징글, 하다, 포테이토, 맛있다, 네, 하하, 용,..."

# 불용어제거

In [ ]:
from kiwipiepy.utils import Stopwords

stopwords = Stopwords()
sw = set([i[0] for i in stopwords.stopwords]) # 중복 제거 위해 set 사용

cleaned_token = []
for i in df["token"]:
  imsi = []
  for w in i:
    if w not in sw:
      imsi.append(w)
  cleaned_token.append(imsi)
df["token"] = cleaned_token
df

,검색어,제목,날짜,본문,댓글,통합본문,token
0,층간소음,층간소음 방지 매트 언제까지 깔아놓으세요?,2026.05.22. 13:19,첫째가 돌무렵부터 깔아놓은 층간소음매트\n지금 그 애가 11살이에요.남자아이라 활동...,[me before U] 둘째 8살까지는...\n[대댓글시비충극혐] 애가 둘이면 더...,층간소음 방지 매트 언제까지 깔아놓으세요 아이가 돌무렵부터 깔아놓은 매트 지금 그 ...,"[층간소음, 방지, 매트, 언제, 깔다, 아이, 돌, 무렵, 깔다, 매트, 지금, ..."
4,층간소음,층간소음 실내화,2026.05.21. 12:54,윗층 노부부 사시는데요\n좋으신분들이에요 오며가며 인사도 하구요\n명절때 너무 시끄...,[고랴니] 기분 나빠할거 같긴 해요,층간소음 실내화 윗집 어르신 사시는데요 좋으신분들이에요 오며가며 인사도 하구요 명절...,"[층간소음, 실내, 집, 어르신, 사다, 좋다, 신분, 오다, 인사, 하다, 명절,..."
5,층간소음,층간소음 직접 말하면 안되죠?,2026.05.21. 07:01,위층집 이사오고부터 밤이고 낮이고 울리는 천장소리..\n새벽2시부터 5시까지 울린적...,[잘먹고잘노는남매맘] 관리소에 전달하세요. 그정도면 핸드폰으로 녹음해 놔도 될거같아...,층간소음 직접 말하면 안되죠 윗집집 이사오고부터 밤이고 낮이고 울리는 천장소리 새벽...,"[층간소음, 직접, 하다, 안되다, 집집, 밤, 낮, 울리다, 천장, 소리, 새벽,..."
8,층간소음,층간소음때문에 이사가는 경우예요,2026.05.20. 06:24,말 안하면 나중에 문제생기나요???,[레몬트라이스] 말해주는집이없을걸요\n[화이트2] 2222222\n[뚜뚜이이] 층간...,층간소음때문에 이사가는 경우예요 말 안하면 나중에 문제생기나요 레몬트라이스 말해주는...,"[층간소음, 사가, 경우, 하다, 나중, 문제, 생기다, 레몬, 트, 라이스, 해주..."
9,층간소음,누수 발생시 관리실,2026.05.19. 08:15,윗집으로 인해 누수가 발생했는데요\n발견한지 일주일 좀 넘었는데\n관리실에서 확인해...,[미쳐가나봄] 누수란게 윗집서 뭘 잠궜다고 금방 해결된 일이 아니예요.\n관리실말처...,누수 발생시 관리사무소 윗집으로 인해 누수가 발생했는데요 발견한지 일주일 좀 넘었는...,"[누수, 발생, 시, 관리, 사무소, 집, 인하다, 누수, 발생, 하다, 발견, 한..."
...,...,...,...,...,...,...,...
2006,발망치,슬리퍼신어도 층간소음,2024.12.17. 09:54,날까요? 대각선집에서 발망치소리가 난다고 문자가와서너무스트레스네요,[이네] 슬리퍼 신어도 발망치소리 나요ㅜㅜ\n[Kangar00] 아이고 그럼 어떻게...,실내화신어도 층간소음 날까요 대각선집에서 층간소음소리가 난다고 문자가와서너무스트레스...,"[실내, 화신, 어도, 층간소음, 날다, 요, 선집, 층간소음, 소리, 나다, 자가..."
2010,발망치,층간소음 기준,2024.12.15. 22:04,층간소음 어디까지 이해해주시나요?,[꼼꼼해용] 네 그럴게요 댓글 감사해요\n[꼼꼼해용] 네 감사해요 좋은 밤 되세요\...,층간소음 기준 층간소음 어디까지 이해해주시나요 꼼꼼해용 네 그럴게요 댓글 감사해요 ...,"[층간소음, 기준, 층간소음, 어디, 이해, 해주다, 꼼꼼하다, 네, 그렇다, 댓글..."
2013,발망치,천장치면 윗집에 들리나요???,2024.12.09. 23:54,층간소음으로 매일 수십번 부수고 싶은 충동이..\n천정치면 윗집에 들릴까요?,[찰옥듀듀] 몰딩이 어디에요??\n[햇빛모자] 아주잘들립니다 주말낮에 청소기만밀어도...,천장치면 윗집에 들리나요 층간소음으로 매일 수십번 부수고 싶은 충동이 천정치면 윗집...,"[장치, 집, 들리다, 층간소음, 매일, 번, 부수, 싶다, 충, 동이, 정치면, ..."
2015,발망치,강아지 방치하면 학대아닌가요?,2024.12.04. 01:31,윗집 이사오고부터\n강아지 짖는 소리에 며칠째 잠을 못자는데\n인터폰도 안받고\n관...,[힐버] 전 요즘 혼자사는 사람들이 많아서 사고도 걱정되드라구요 ㅠ 혹시 무슨일 생...,강아지 방치하면 학대아닌가요 윗집 이사오고부터 강아지 짖는 소리에 며칠째 잠을 못자...,"[강아지, 방치, 하다, 학대, 아니다, 집, 강아지, 짖다, 소리, 며칠, 잠, ..."
2018,발망치,안마기 소리에 깼어요,2024.12.01. 05:59,징글징글 합니다 ㅜㅜ,[포테이토는 맛있지] ㅜㅜ 네\n[하하하요용] 안마기 소린진 런닝머신 소린지 규칙적...,안마기 소리에 깼어요 징글징글 합니다 포테이토는 맛있지 네 하하하요용 안마기 소린진...,"[안마, 소리, 깨다, 징글징글, 하다, 포테이토, 맛있다, 네, 하하, 용, 안마..."

In [ ]:
# 결과를 CSV 파일로 저장 (한글 깨짐 방지 및 인덱스 제외)
file_name = "레몬테라스_데이터전처리완료.csv"
df.to_csv(file_name, index=False, encoding="utf-8-sig")